/* Generated by tools/gen_course_relocs.py; no ROM data. */
#pragma once
#include <stdint.h>
#define MK64_RELOC_TABLE_COUNT 32u
#define MK64_RELOC_RECIPE_BYTES 8040u
#define MK64_RELOC_POINTER_BYTES 8072u
void mk64_course_relocs_apply(uint8_t *region);
