/* Generated by tools/gen_course_segments.py; no ROM data. */
#pragma once
#include <stdint.h>
enum { MK64_STATIC_COMMON, MK64_STATIC_CEREMONY, MK64_STATIC_LOGO };
const void *mk64_course_segment_lookup(unsigned course, unsigned segment, uint32_t offset);
const void *mk64_static_segment_lookup(unsigned dataset, uint32_t offset);
