"""Generate per-TU save symbol tables, including private static callbacks.

IDs are FNV-1a of kind/source-file/symbol-name, never table positions or addresses.
Adding a symbol does not renumber existing saves. Collisions fail the build.
"""
import argparse
from pathlib import Path
import re

def symbol_id(key):
    value = 2166136261
    for byte in key.encode('ascii'):
        value = ((value ^ byte) * 16777619) & 0xffffffff
    if not value:
        raise ValueError('Reserved zero symbol ID: ' + key)
    return value

def generate(game, output):
    tables = []
    ids = {}
    total = [0, 0]
    function = re.compile(r'^\s*(?:static\s+)?(?:[A-Za-z_]\w*\s+|\*\s*)+([A-Za-z_]\w*)\s*\([^;{}]*\)\s*\{', re.M)
    for source in sorted(game.glob('*.c')):
        if not source.name.startswith(('g_', 'm_', 'p_')):
            continue
        text = re.sub(r'/\*.*?\*/|//[^\n]*', '', source.read_text(), flags=re.S)
        # The imported game has disabled #if 0 functions and movement tables.
        active, conditional, filtered = True, [], []
        for line in text.splitlines(keepends=True):
            directive = re.match(r'\s*#\s*(if|ifdef|ifndef|else|endif)\b(.*)', line)
            if directive:
                command, expression = directive.groups()
                if command in ('if', 'ifdef', 'ifndef'):
                    enabled = not (command == 'if' and expression.strip() == '0')
                    conditional.append((active, enabled))
                    active = active and enabled
                elif command == 'else':
                    parent, enabled = conditional[-1]
                    conditional[-1] = (parent, not enabled)
                    active = parent and not enabled
                elif command == 'endif':
                    active = conditional.pop()[0]
            filtered.append(line if active else '\n')
        text = ''.join(filtered)
        # Only top-level definitions; "else if (...) {" is not a function.
        text = re.sub(r'"(?:\\.|[^"\\])*"|\'(?:\\.|[^\'\\])*\'', lambda m: ' ' * len(m.group()), text)
        depths, depth = [], 0
        for character in text:
            depths.append(depth)
            depth += (character == '{') - (character == '}')
        functions = [m.group(1) for m in function.finditer(text)
                     if depths[m.start()] == 0 and m.group(1) not in ('if', 'for', 'while', 'switch')]
        groups = [('function', functions),
                  ('movement', re.findall(r'^\s*(?:static\s+)?mmove_t\s+(\w+)\s*=\s*\{', text, re.M))]
        lines = ['/* Generated by generate_save_symbols.py. */', '#include "save_symbols.h"']
        for kind, names in groups:
            table = f'q2_save_{source.stem}_{kind}'
            lines.append(f'const q2_save_symbol_t {table}[] = {{')
            for name in sorted(set(names)):
                key = f'{kind}:{source.name}:{name}'
                identity = symbol_id(key)
                if identity in ids:
                    raise ValueError(f'Save symbol collision: {key} / {ids[identity]}')
                ids[identity] = key
                address = name if kind == 'function' else '&' + name
                lines.append(f'    {{0x{identity:08x}u, (uintptr_t){address}}},')
                total[kind == 'movement'] += 1
            lines.extend(['    {0, 0}', '};'])
            tables.append((table, kind == 'movement'))
        path = output / 'save_symbols' / (source.stem + '.inc')
        path.parent.mkdir(parents=True, exist_ok=True)
        result = '\n'.join(lines) + '\n'
        if not path.exists() or path.read_text() != result:
            path.write_text(result)
    registry = ['#include "save_symbols.h"']
    registry.extend(f'extern const q2_save_symbol_t {table}[];' for table, _ in tables)
    registry.append('const q2_save_table_t q2_save_tables[] = {')
    registry.extend(f'    {{{table}, {int(movement)}}},' for table, movement in tables)
    registry.extend(['    {NULL, 0}', '};'])
    path = output / 'save_registry.c'
    result = '\n'.join(registry) + '\n'
    if not path.exists() or path.read_text() != result:
        path.write_text(result)
    print(f'Save registry: {total[0]} functions, {total[1]} movements; IDs collision-free')

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--game', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    generate(args.game, args.output)
