#!/usr/bin/env python3
"""Generate ROM-independent pointer tables from the decomp's course sources."""

import json
import pathlib
import re

import yaml


def structured_fixups(root, by_name):
    """Rebuild pointer-bearing structures that raw byte matching cannot relocate."""
    source = (root / "src/data/textures.c").read_text()
    patches = []
    spans = sorted(row["off"] for row in by_name.values())
    for name, count, body in re.findall(
        r"MkAnimation\s+(\w+)\[(\d+)\]\s*=\s*\{(.*?)\};", source, re.S
    ):
        rows = re.findall(r"\{\s*(\w+)\s*,\s*(0x[0-9A-Fa-f]+|\d+)\s*\}", body)
        offset = by_name[name]["off"]
        end = next((value for value in spans if value > offset), offset)
        if len(rows) != int(count) or offset + len(rows) * 8 > end:
            raise ValueError(f"Invalid animation span for {name}")
        for index, (target, frames) in enumerate(rows):
            if target != "NULL" and target not in by_name:
                raise ValueError(f"Unknown animation texture {target}")
            pointer = "0" if target == "NULL" else f"(uintptr_t){target}"
            patches.extend(((offset + index * 8, pointer),
                            (offset + index * 8 + 4, frames)))

    # Named segment-2 descriptors lack an address in their symbol name.
    # Short byte matches confused letters that differ only in pointer operands.
    for name, count, body in re.findall(
        r"MenuTexture\s+(\w+)\[(\d+)\]\s*=\s*\{(.*?)\};", source, re.S
    ):
        if not name.startswith("seg2_textureFont") or name not in by_name:
            continue
        rows = re.findall(r"\{([^{}]+)\}", body)
        offset = by_name[name]["off"]
        end = next((value for value in spans if value > offset), offset)
        if len(rows) != int(count) or offset + len(rows) * 20 > end:
            raise ValueError(f"Invalid menu descriptor span for {name}")
        for index, row in enumerate(rows):
            fields = [value.strip() for value in row.split(",")]
            if len(fields) != 8:
                raise ValueError(f"Invalid menu descriptor {name}")
            target = fields[1]
            if target != "NULL" and target not in by_name:
                raise ValueError(f"Unknown menu texture {target}")
            scalar = [int(value, 0) & 0xFFFF for value in fields[:1] + fields[2:]]
            values = (f"{scalar[0]}u", "0" if target == "NULL" else f"(uintptr_t){target}",
                      f"{scalar[1] | (scalar[2] << 16)}u",
                      f"{scalar[3] | (scalar[4] << 16)}u",
                      f"{scalar[5] | (scalar[6] << 16)}u")
            patches.extend((offset + index * 20 + word * 4, value)
                           for word, value in enumerate(values))

    source = (root / "courses/courseTable.c").read_text()
    vertices = re.findall(r"\bd_course_\w+_vertex\b", source)
    textures = re.findall(r"\b\w+_textures\b", source)
    if len(vertices) != 20 or len(textures) != 20:
        raise ValueError("Expected 20 course vertex/texture pairs")
    offset = by_name["gCourseTable"]["off"]
    for index, (vertex, texture) in enumerate(zip(vertices, textures)):
        if vertex not in by_name or texture not in by_name:
            raise ValueError(f"Missing course asset for {index}")
        patches.extend(((offset + index * 48 + 24, f"(uintptr_t){vertex}"),
                        (offset + index * 48 + 40, f"(uintptr_t){texture}")))
    if len(dict(patches)) != len(patches):
        raise ValueError("Overlapping structured fixups")
    return patches


def main() -> None:
    root = pathlib.Path(__file__).resolve().parents[1]
    recipes = json.loads((root / "tools/psp/recipes.json").read_text())["recipes"]
    by_name = {r["name"]: r for r in recipes}
    sources = list((root / "courses").glob("*/course_offsets.c"))
    sources += list((root / "courses").glob("*/course_data.c"))
    sources.append(root / "src/data/some_data.c")
    output = [
        "/* Generated by tools/gen_course_relocs.py; no ROM data. */",
        '#include "course_relocs.h"',
        "#include <stdint.h>",
        "#include <string.h>",
    ]
    tables = []
    symbols = set()
    for recipe in recipes:
        if recipe["kind"] != "RELOCS" or recipe["name"] in {
            "D_800DCBB4", "gCoursePathTable2", "gCoursePathTable", "cpu_BehaviourLUT"
        }:
            continue
        matches = []
        for path in sources:
            source = path.read_text(errors="replace")
            pattern = r"\b" + re.escape(recipe["name"]) + r"\s*\[[^]]*\]\s*=\s*\{(.*?)\};"
            match = re.search(pattern, source, re.S)
            if match:
                matches.append((path, match.group(1)))
            if recipe["name"] == "D_800E5DB0" and not match:
                single = re.search(r"\bD_800E5DB0\s*=\s*(&\w+)\s*;", source)
                if single:
                    matches.append((path, single.group(1)))
        if len(matches) != 1:
            raise ValueError(f"Expected one definition of {recipe['name']}: {matches}")
        body = re.sub(r"/\*.*?\*/|//[^\n]*", "", matches[0][1], flags=re.S)
        items = [item.strip().removeprefix("&") for item in body.split(",") if item.strip()]
        if len(items) * 4 != recipe["size"] + 1:
            raise ValueError(f"Unexpected pointer count for {recipe['name']}")
        for item in items:
            if item not in by_name or not re.fullmatch(r"[A-Za-z_]\w*", item):
                raise ValueError(f"Unknown asset pointer {item} in {recipe['name']}")
            symbols.add(item)
        tables.append((recipe["off"], items))

    metadata = []
    for path in (root / "yamls/courses").glob("*_metadata.yml"):
        course = yaml.safe_load(path.read_text())["course"]
        metadata.append(course)
    metadata.sort(key=lambda course: course["id"])
    if [course["id"] for course in metadata] != list(range(21)):
        raise ValueError("Expected metadata for all 21 course IDs")
    metadata_fields = {
        "D_800DCBB4": "D_800DCBB4",
        "gCoursePathTable2": "path_table",
        "gCoursePathTable": "path_table_unknown",
        "cpu_BehaviourLUT": "cpu_behaviour_ptr",
    }
    for name, field in metadata_fields.items():
        items = []
        for course in metadata:
            value = course[field]
            items.extend(value if isinstance(value, list) else [value])
        items = [item.removeprefix("&") for item in items]
        recipe = by_name[name]
        if len(items) * 4 != recipe["size"] + 1:
            raise ValueError(f"Unexpected pointer count for {name}")
        for item in items:
            if item not in by_name:
                raise ValueError(f"Unknown metadata pointer {item} in {name}")
            symbols.add(item)
        tables.append((recipe["off"], items))

    expected = {recipe["off"] for recipe in recipes if recipe["kind"] == "RELOCS"}
    actual = [offset for offset, _ in tables]
    if len(actual) != len(expected) or set(actual) != expected:
        raise ValueError("Relocation tables do not cover all recipes exactly once")

    patches = structured_fixups(root, by_name)
    symbols.update(value.removeprefix("(uintptr_t)") for _, value in patches
                   if value.startswith("(uintptr_t)"))
    for symbol in sorted(symbols):
        output.append(f"extern const unsigned char {symbol}[];")
    for index, (_, items) in enumerate(tables):
        output.append(f"static const uintptr_t table_{index}[] = {{")
        output.extend(f"    (uintptr_t){item}," for item in items)
        output.append("};")
    output.append("static const struct { uint32_t offset; uintptr_t value; } fixups[] = {")
    output.extend(f"    {{{offset}u, {value}}}," for offset, value in patches)
    output.append("};")
    output.append("void mk64_course_relocs_apply(uint8_t *region) {")
    for index, (offset, items) in enumerate(tables):
        output.append(f"    memcpy(region + {offset}u, table_{index}, {len(items) * 4}u);")
    output.append("    for (unsigned i = 0; i < sizeof(fixups) / sizeof(fixups[0]); ++i) {")
    output.append("        uint32_t value = (uint32_t)fixups[i].value;")
    output.append("        memcpy(region + fixups[i].offset, &value, sizeof(value));")
    output.append("    }")
    output.append("}")
    (root / "course_relocs.c").write_text("\n".join(output) + "\n")
    (root / "course_relocs.h").write_text(
        "/* Generated by tools/gen_course_relocs.py; no ROM data. */\n"
        "#pragma once\n#include <stdint.h>\n"
        f"#define MK64_RELOC_TABLE_COUNT {len(tables)}u\n"
        f"#define MK64_RELOC_RECIPE_BYTES {sum(len(i) * 4 - 1 for _, i in tables)}u\n"
        f"#define MK64_RELOC_POINTER_BYTES {sum(len(i) * 4 for _, i in tables)}u\n"
        "void mk64_course_relocs_apply(uint8_t *region);\n"
    )
    print(f"Wrote {len(tables)} asset pointer tables ({sum(len(i) for _, i in tables)} pointers)")


if __name__ == "__main__":
    main()
