#!/usr/bin/env python3
"""Build course segmented-address maps from decomp headers and ROM recipes."""

import json
import pathlib
import re

import yaml
from yaml_unique import load as load_yaml
from gen_recipe_index import course_model_locations, correct_structured_recipes


COURSES = (
    "mario_raceway", "choco_mountain", "bowsers_castle", "banshee_boardwalk",
    "yoshi_valley", "frappe_snowland", "koopa_troopa_beach", "royal_raceway",
    "luigi_raceway", "moo_moo_farm", "toads_turnpike", "kalimari_desert",
    "sherbet_land", "rainbow_road", "wario_stadium", "block_fort",
    "skyscraper", "double_deck", "dks_jungle_parkway", "big_donut",
)
DECL = re.compile(r"^extern\s+[^;]*?\s+(\w+)\s*\[[^]]*\]\s*;", re.M)


def entries(path: pathlib.Path, segment: int, recipes: dict) -> list:
    result = {}
    models = course_model_locations(path.with_suffix(".c"), recipes) if segment == 6 else {}
    # A source list can be used by the course's own tables without an extern
    # declaration (Yoshi Valley dl_CC0). Include recovered source arrays too.
    names = dict.fromkeys(DECL.findall(path.read_text(errors="replace")))
    names.update(dict.fromkeys(models))
    for name in names:
        dl = re.search(r"_dl_([0-9A-Fa-f]+)$", name)
        raw = re.search(r"_0([0-9A-Fa-f])([0-9A-Fa-f]{6})$", name)
        if dl:
            offset = int(dl.group(1), 16)
        elif raw and int(raw.group(1), 16) == segment:
            offset = int(raw.group(2), 16)
        elif name in models:
            offset = models[name]
        else:
            continue
        if name not in recipes:
            raise ValueError(f"Missing ROM recipe for {name}")
        if offset in result and result[offset][0] != recipes[name]["off"]:
            raise ValueError(f"Conflicting segment offset in {path}: {offset:#x}")
        result[offset] = (recipes[name]["off"], recipes[name]["size"])
    return sorted(result.items())


def main() -> None:
    root = pathlib.Path(__file__).resolve().parents[1]
    data = json.loads((root / "tools/psp/recipes.json").read_text())
    correct_structured_recipes(data, root)
    recipes = {r["name"]: r for r in data["recipes"]}
    lines = [
        "/* Generated by tools/gen_course_segments.py; no ROM data. */",
        '#include "course_segments.h"',
        '#include "resident.h"',
        "typedef struct { uint32_t segment_offset, end_offset, asset_offset; } segment_entry_t;",
    ]
    descriptors = []
    total = 0
    for course in COURSES:
        arrays = []
        for segment, filename in ((6, "course_data.h"),
                                  (7, "course_displaylists.inc.h")):
            rows = entries(root / "courses" / course / filename, segment, recipes)
            name = f"seg{segment}_{course}"
            arrays.append((name, len(rows)))
            lines.append(f"static const segment_entry_t {name}[] = {{")
            if not rows:
                lines.append("    {0u, 0u, 0u},")
            for i, (off, (asset, size)) in enumerate(rows):
                end = rows[i + 1][0] if i + 1 < len(rows) else off + size + 1
                lines.append(f"    {{0x{off:06x}u, 0x{end:06x}u, {asset}u}},")
            lines.append("};")
            total += len(rows)
        descriptors.append(arrays)
    lines.append("static const struct { const segment_entry_t *seg6, *seg7;"
                 " uint16_t count6, count7; } courses[] = {")
    for pair in descriptors:
        lines.append(f"    {{{pair[0][0]}, {pair[1][0]}, {pair[0][1]}u, {pair[1][1]}u}},")
    lines.append("};")
    static_maps = []
    for label, filename in (("common", "common_data.yml"),
                            ("ceremony", "ceremony_data.yml"),
                            ("logo", "startup_logo.yml")):
        document = load_yaml((root / "yamls/us" / filename).read_text())
        candidates = []
        for symbol, item in document.get(":config", {}).get("tables", {}).items():
            if isinstance(item, dict) and "range" in item:
                candidates.append((symbol, item["range"][0]))
        for item in document.values():
            if isinstance(item, dict) and "symbol" in item and "offset" in item:
                candidates.append((item["symbol"], item["offset"]))
        if label == "common":
            # Shell sprite quads and another shared quad were extracted as
            # anonymous batches, without entries in the source YAML.
            for symbol in recipes:
                batch = re.fullmatch(r"common_data_seg13_vtx_([0-9A-Fa-f]+)", symbol)
                if batch:
                    candidates.append((symbol, int(batch.group(1), 16)))
        if label == "ceremony":
            # The YAML starts at the first trophy DL (0xFE0), while the
            # extracted anonymous vertex batches begin at segment offset 0.
            for symbol in recipes:
                batch = re.fullmatch(r"ceremony_data_seg11_vtx_([0-9A-Fa-f]+)", symbol)
                if batch:
                    candidates.append((symbol, int(batch.group(1), 16)))
        if label == "logo":
            # The YAML names display lists and textures, but the logo's
            # quadrangles also load anonymous vertices below the first DL.
            for symbol in recipes:
                batch = re.fullmatch(r"startup_logo_seg6_vtx_([0-9A-Fa-f]+)", symbol)
                if batch:
                    candidates.append((symbol, int(batch.group(1), 16)))
        by_offset = {}
        for symbol, offset in candidates:
            # YAML mixes full N64 addresses (0x0D001CE8) and offsets (0x1EE8).
            # The resolver has already removed the segment byte.
            offset &= 0xFFFFFF
            if label == "logo" and symbol == "reflection_map_gold":
                # The PSP build renames the logo copy because the ceremony
                # segment declares another asset with the same YAML symbol.
                symbol = "reflection_map_gold_logo"
            if symbol not in recipes:
                continue  # APPEND entries folded into a parent asset symbol
            asset = recipes[symbol]
            if offset in by_offset and by_offset[offset][0] != asset["off"]:
                raise ValueError(f"Conflicting {label} offset {offset:#x}")
            by_offset[offset] = (asset["off"], asset["size"])
        rows = sorted(by_offset.items())
        if not rows:
            raise ValueError(f"Empty {label} segment map")
        name = f"seg_static_{label}"
        lines.append(f"static const segment_entry_t {name}[] = {{")
        for i, (offset, (asset_offset, size)) in enumerate(rows):
            end = rows[i + 1][0] if i + 1 < len(rows) else offset + size + 1
            lines.append(f"    {{0x{offset:06x}u, 0x{end:06x}u, {asset_offset}u}},")
        lines.append("};")
        static_maps.append((name, len(rows)))
        total += len(rows)
    lines.append("static const struct { const segment_entry_t *entries; uint16_t count; } static_maps[] = {")
    lines.extend(f"    {{{name}, {count}u}}," for name, count in static_maps)
    lines.append("};")
    lines.extend([
        "const void *mk64_static_segment_lookup(unsigned dataset, uint32_t offset) {",
        "    if (dataset >= sizeof(static_maps) / sizeof(static_maps[0])) return NULL;",
        "    const segment_entry_t *entries = static_maps[dataset].entries;",
        "    unsigned low = 0, high = static_maps[dataset].count;",
        "    while (low < high) {",
        "        unsigned middle = low + (high - low) / 2;",
        "        if (entries[middle].segment_offset <= offset) low = middle + 1;",
        "        else high = middle;",
        "    }",
        "    if (low == 0 || offset >= entries[low - 1].end_offset) return NULL;",
        "    return gMk64AssetRegion + entries[low - 1].asset_offset +",
        "           (offset - entries[low - 1].segment_offset);",
        "}",
    ])
    lines.extend([
        "const void *mk64_course_segment_lookup(unsigned course, unsigned segment, uint32_t offset) {",
        "    if (course >= sizeof(courses) / sizeof(courses[0]) || segment < 6 || segment > 7)",
        "        return NULL;",
        "    const segment_entry_t *entries = segment == 6 ? courses[course].seg6 : courses[course].seg7;",
        "    unsigned high = segment == 6 ? courses[course].count6 : courses[course].count7;",
        "    unsigned low = 0;",
        "    while (low < high) {",
        "        unsigned middle = low + (high - low) / 2;",
        "        if (entries[middle].segment_offset <= offset) low = middle + 1;",
        "        else high = middle;",
        "    }",
        "    if (low == 0) return NULL;",
        "    if (offset >= entries[low - 1].end_offset) return NULL;",
        "    return gMk64AssetRegion + entries[low - 1].asset_offset +",
        "           (offset - entries[low - 1].segment_offset);",
        "}",
    ])
    (root / "course_segments.c").write_text("\n".join(lines) + "\n")
    (root / "course_segments.h").write_text(
        "/* Generated by tools/gen_course_segments.py; no ROM data. */\n"
        "#pragma once\n#include <stdint.h>\n"
        "enum { MK64_STATIC_COMMON, MK64_STATIC_CEREMONY, MK64_STATIC_LOGO };\n"
        "const void *mk64_course_segment_lookup(unsigned course, unsigned segment, uint32_t offset);\n"
        "const void *mk64_static_segment_lookup(unsigned dataset, uint32_t offset);\n"
    )
    print(f"Wrote {total} segment entries")


if __name__ == "__main__":
    main()
