#!/usr/bin/env python3
"""Generate ROM-data-free C declarations from the decomp asset manifests."""

from pathlib import Path

from yaml_unique import load as load_yaml


ASSETS = (
    "common_data", "startup_logo", "ceremony_data", "data_800E8700",
    "data_800E45C0",
)


def declaration(item: dict) -> str:
    kind = item["type"]
    if kind == "gfx":
        ctype = "Gfx"
    elif kind in ("vtx", "VTX"):
        ctype = "Vtx"
    elif kind == "texture":
        ctype = item.get("ctype", "u8")
    elif kind == "lights":
        ctype = "Lights1"
    elif kind == "mtx":
        ctype = "Mtx"
    elif kind == "mk64:track_path":
        ctype = "TrackPathPoint"
    elif kind == "mk64:item_curve":
        ctype = "u8"
    elif kind == "mk64:driving_behaviour":
        ctype = "CPUBehaviour"
    elif kind == "inc":
        ctype = item["ctype"]
    elif kind == "array":
        ctype = item["array_type"]
    else:
        raise ValueError(f"Unknown asset kind {kind}: {item['symbol']}")
    # An incomplete array also covers entries folded into a parent ROM recipe.
    if item["symbol"] == "D_800E8900":
        # The APPEND table is indexed as three groups of four vertices.
        return "extern Vtx D_800E8900[][4];"
    if kind == "lights" and item["symbol"] != "D_800E45C0":
        return f"extern Lights1 {item['symbol']};"
    return f"extern {ctype} {item['symbol']}[];"


def table_declaration(symbol: str, manifest: dict) -> str:
    start = manifest[":config"]["tables"][symbol]["range"][0]
    for item in manifest.values():
        if not isinstance(item, dict) or item.get("type") != "texture" or item.get("offset") != start:
            continue
        ctype = item.get("ctype", "u8")
        size = item.get("size")
        if size is None:
            if item["format"].lower() == "tlut":
                size = item["colors"] * 2
            else:
                bits = int(''.join(ch for ch in item["format"] if ch.isdigit()))
                size = (item["width"] * item["height"] * bits + 7) // 8
        element_size = {"u8": 1, "u16": 2, "u32": 4}[ctype]
        if size % element_size:
            raise ValueError(f"Unaligned texture group {symbol}")
        return f"extern {ctype} {symbol}[][{size // element_size}];"
    ctype = "u16" if symbol.startswith("common_tlut_") else "u8"
    return f"extern {ctype} {symbol}[];"


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    output = root / "include/assets"
    output.mkdir(parents=True, exist_ok=True)
    for name in ASSETS:
        manifest = load_yaml((root / "yamls/us" / f"{name}.yml").read_text())
        guard = f"MK64_GENERATED_{name.upper()}_H"
        lines = [
            "/* Generated by tools/gen_asset_headers.py from the source YAML; no ROM data. */",
            f"#ifndef {guard}", f"#define {guard}",
            "#include <ultra64.h>", "#include <common_structs.h>",
        ]
        if name == "ceremony_data":
            lines.append("#include <path.h>")
        seen = set()
        for item in manifest.values():
            if not isinstance(item, dict) or "symbol" not in item:
                continue
            symbol = item["symbol"]
            if symbol in seen:
                raise ValueError(f"Duplicate asset symbol: {symbol}")
            seen.add(symbol)
            lines.append(declaration(item))
        # APPEND tables name complete groups of ROM assets. Their children
        # appear below as individual YAML entries, but game code uses both.
        for symbol in manifest.get(":config", {}).get("tables", {}):
            if symbol not in seen:
                lines.append(table_declaration(symbol, manifest))
                seen.add(symbol)
        lines += [f"#endif /* {guard} */", ""]
        (output / f"{name}.h").write_text("\n".join(lines))
        print(f"{name}: {len(seen)} declarations")


if __name__ == "__main__":
    main()
