#!/usr/bin/env python3
"""Generate ROM-independent course metadata initializers from source YAML."""

import json
from pathlib import Path

import yaml


FIELDS = {
    "gCourseNames": "name",
    "gCourseDebugNames": "debug_name",
    "gPerCupIndexByCourseId": "cup_index",
    "gCupSelectionByCourseId": "cup",
    "sCourseLengths": "course_length",
    "cpu_BehaviourLUT": "cpu_behaviour_ptr",
    "gCoursePathTableUnknown": "path_table_unknown",
    "gCoursePathTable": "path_table",
    "cpu_SteeringSensitivity": "cpu_steering_sensitivity",
    "cpu_CourseMaximumSeparation": "cpu_maximum_separation",
    "cpu_CourseMinimumSeparation": "cpu_minimum_separation",
    "D_800DCBB4": "D_800DCBB4",
    "gBombKartSpawns": "bomb_kart_spawns",
    "gCoursePathSizes": "path_sizes",
    "sSkyColors": "sky_colors",
    "sSkyColors2": "sky_colors2",
}

SYMBOL_FIELDS = {
    "cpu_BehaviourLUT", "gCoursePathTableUnknown", "gCoursePathTable",
    "D_800DCBB4", "gCupSelectionByCourseId",
}
STRING_FIELDS = {"gCourseNames", "gCourseDebugNames", "sCourseLengths"}


def value(item, symbols=False, strings=False):
    if isinstance(item, list):
        return "{" + ", ".join(value(x, symbols, strings) for x in item) + "}"
    if item is None:
        return "NULL" if strings or symbols else "0"
    if isinstance(item, str):
        if symbols:
            return item
        if strings:
            return json.dumps(item)
        return item  # Float literals in YAML carry their explicit f suffix.
    if isinstance(item, float):
        return repr(item) + "f"
    return str(item)


def main():
    root = Path(__file__).resolve().parents[1]
    inputs = list((root / "yamls/courses").glob("*_metadata.yml"))
    courses = [yaml.safe_load(path.read_text())["course"] for path in inputs]
    courses.sort(key=lambda course: course["id"])
    if len(courses) != 21 or [c["id"] for c in courses] != list(range(21)):
        raise ValueError("Expected 21 unique course IDs, 0 through 20")
    output = root / "include/assets/course_metadata"
    output.mkdir(parents=True, exist_ok=True)
    for filename, field in FIELDS.items():
        lines = ["/* Generated by tools/gen_course_metadata.py from source YAML. */"]
        for course in courses:
            entry = course[field]
            if filename == "gCupSelectionByCourseId" and entry is None:
                entry = -1  # The ceremony is not part of a cup.
            if filename == "gCoursePathSizes":
                # The C structure has five u16 values and six pad bytes.
                if len(entry) != 8 or any(entry[5:]):
                    raise ValueError(f"Unexpected path sizes for course {course['id']}")
                entry = entry[:5]
            lines.append("    " + value(entry, filename in SYMBOL_FIELDS,
                                        filename in STRING_FIELDS) + ",")
        (output / f"{filename}.inc.c").write_text("\n".join(lines) + "\n")
    print(f"Generated {len(FIELDS)} metadata fragments for {len(courses)} courses")


if __name__ == "__main__":
    main()
